modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/BaseBean.java
/*
 * Copyright (C) 2010 Interactive Media Management
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.DataNotFoundException;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.ejb.facades.UserFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;

/**
 * Base bean providing useful methods for JSF managed beans.
 *
 * @author Allan Lykke Christensen
 */
public abstract class BaseBean {

    protected static final Logger LOG = Logger.getLogger(BaseBean.class.getName());

    @EJB private UserFacadeLocal userFacade;

    private UserAccount currentUserAccount;

    /**
     * Gets the current user, or {@code null} if the user is not logged in.
     *
     * @return Current user logged in.
     */
    public UserAccount getUser() {
        if (currentUserAccount == null) {
            FacesContext ctx = FacesContext.getCurrentInstance();
            String uid = ctx.getExternalContext().getRemoteUser();

            // Used by the session overview to see the name of the users logged in
            JsfUtils.getHttpSession().setAttribute("uid", uid);

            if (uid != null || !uid.isEmpty()) {
                try {
                    currentUserAccount = userFacade.findById(uid);
                } catch (DataNotFoundException ex) {
                    LOG.log(Level.INFO, "User [{0}] could not be found", uid);
                }
            }

        }
        return currentUserAccount;
    }

    /**
     * Determines if the current user is in a given role.
     *
     * @param role
     *          Name of the role
     * @return <code>true</code> if the user is in the given role, otherwise
     *         <code>false</code>
     */
    public boolean isUserInRole(String role) {
        FacesContext ctx = FacesContext.getCurrentInstance();
        return ctx.getExternalContext().isUserInRole(role);
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Bundle.java
/*
 * Copyright (C) 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

/**
 * Identifier of {@link java.util.ResourceBundle}s available in
 * {@code FacesContext.xml}.
 *
 * @author Allan Lykke Christensen
 */
public enum Bundle {

    /**
     * Old ResourceBundle containing messages.
     *
     * @deprecated Use {@link Bundle#i18n}
     */
    msgs,
    /**
     * Old ResourceBundle containing resources.
     *
     * @deprecated Use {@link Bundle#i18n}
     */
    res,
    /**
     * ResourceBundle containing messages and resources for the web application.
     */
    i18n;
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/ClassificationDialog.java
/*
 * Copyright (C) 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.metadata.Concept;
import dk.i2m.converge.core.metadata.Subject;
import dk.i2m.converge.ejb.facades.MetaDataFacadeLocal;
import dk.i2m.converge.ejb.services.MetaDataServiceLocal;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.event.ActionEvent;
import org.richfaces.component.html.HtmlTree;
import org.richfaces.event.NodeSelectedEvent;

/**
 * JSF backing bean for the classification dialog.
 *
 * @author Allan Lykke Christensen
 */
public class ClassificationDialog {

    @EJB private MetaDataFacadeLocal metaDataFacade;

    @EJB private MetaDataServiceLocal metaDataService;

    /** Name of the {@link Concept}. */
    private String name = "";

    /** Definition of the {@link Concept}. */
    private String definition = "";

    /** Type of the {@link Concept}. */
    private String type = "";

    /** List of selected {@link Concept}s. */
    private List<Concept> selectedConcepts = new ArrayList<Concept>();

    /**
     * Creates a new instance of {@link ClassificationDialog}.
     */
    public ClassificationDialog() {
    }

    /**
     * Event handler for resetting the entry of a new {@link Concept}.
     * <p/>
     * @param event Event that invoked the handler
     */
    public void onReset(ActionEvent event) {
        this.name = "";
        this.definition = "";
        this.type = "";
    }

    /**
     * Event handler for removing all selected {@link Concept}s.
     * <p/>
     * @param event Event that invoked the handler
     */
    public void onRemoveAll(ActionEvent event) {
        selectedConcepts = new ArrayList<Concept>();
    }
    
    public void onSelectSubject(NodeSelectedEvent event) {
        HtmlTree tree = (HtmlTree) event.getComponent();
        Subject subj = (Subject) tree.getRowData();
        selectedConcepts.add(subj);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Common.java
/*
 * Copyright (C) 2010 - 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later 
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.Announcement;
import dk.i2m.converge.core.Color;
import dk.i2m.converge.core.ConfigurationKey;
import dk.i2m.converge.core.calendar.EventCategory;
import dk.i2m.converge.core.content.AssignmentType;
import dk.i2m.converge.core.content.Language;
import dk.i2m.converge.core.content.NewsItemField;
import dk.i2m.converge.core.content.catalogue.Catalogue;
import dk.i2m.converge.core.content.catalogue.MediaItemStatus;
import dk.i2m.converge.core.content.catalogue.Rendition;
import dk.i2m.converge.core.content.forex.Currency;
import dk.i2m.converge.core.content.markets.FinancialMarket;
import dk.i2m.converge.core.content.weather.Location;
import dk.i2m.converge.core.content.weather.Situation;
import dk.i2m.converge.core.metadata.*;
import dk.i2m.converge.core.newswire.NewswireService;
import dk.i2m.converge.core.plugin.*;
import dk.i2m.converge.core.security.*;
import dk.i2m.converge.core.workflow.*;
import dk.i2m.converge.ejb.facades.*;
import dk.i2m.converge.ejb.services.NewswireServiceLocal;
import dk.i2m.jsf.JsfUtils;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.Application;
import javax.faces.context.FacesContext;
import org.apache.commons.lang.StringUtils;

/**
 * JSF application bean containing common data.
 *
 * @author Allan Lykke Christensen
 */
public class Common {

    private static final Logger LOG = Logger.getLogger(Common.class.toString());

    @EJB
    private CalendarFacadeLocal calendarFacade;

    @EJB
    private UserFacadeLocal userFacade;

    @EJB
    private OutletFacadeLocal outletFacade;

    @EJB
    private SystemFacadeLocal systemFacade;

    @EJB
    private WorkflowFacadeLocal workflowFacade;

    @EJB
    private MetaDataFacadeLocal metaDataFacade;

    @EJB
    private NewswireServiceLocal newswireService;

    @EJB
    private CatalogueFacadeLocal catalogueFacade;

    @EJB
    private ListingFacadeLocal listingFacade;

    private ResourceBundle i18n = JsfUtils.getResourceBundle(Bundle.i18n.name());

    /**
     * Get the local time on the server.
     *
     * @return Local time on the server
     */
    public Date getLocalTime() {
        return java.util.Calendar.getInstance().getTime();
    }

    public TimeZone getSystemTimeZone() {
        try {
            String timeZone = systemFacade.getProperty(ConfigurationKey.TIME_ZONE);
            return TimeZone.getTimeZone(timeZone);
        } catch (Exception ex) {
            LOG.log(Level.WARNING, "Could not obtain system time zone", ex.getMessage());
            return TimeZone.getDefault();
        }
    }

    /**
     * Gets the dynamic {@link UserRole}s of the system.
     *
     * @return {@link Map} of dynamic {@link UserRole}s.
     */
    public Map<String, UserRole> getUserRoles() {
        List<UserRole> original = userFacade.getUserRoles();
        Map<String, UserRole> map = new LinkedHashMap<String, UserRole>();

        for (UserRole userRole : original) {
            map.put(userRole.getName(), userRole);
        }

        return map;
    }

    /**
     * Gets a {@link Map} of available colors.
     *
     * @return {@link Map} of available colors
     */
    public Map<String, String> getColorSwatch() {
        Map<String, String> swatch = new LinkedHashMap<String, String>();

        for (Color color : Color.values()) {
            swatch.put(i18n.getString("Generic_COLOR_" + color.name().toLowerCase()), color.name().toLowerCase());
        }

        return swatch;
    }

    /**
     * Gets a {@link Map} of {@link Outlet}s from the database.
     *
     * @return {@link Map} of {@link Outlet}s from the database.
     */
    public Map<String, Outlet> getOutlets() {
        List<Outlet> original = outletFacade.findAllOutlets();
        Map<String, Outlet> map = new LinkedHashMap<String, Outlet>();

        for (Outlet outlet : original) {
            map.put(outlet.getTitle(), outlet);
        }

        return map;
    }

    /**
     * Gets a {@link Map} of {@link Workflow}s from the database.
     *
     * @return {@link Map} of {@link Workflow}s from the database.
     */
    public Map<String, Workflow> getWorkflows() {
        List<Workflow> original = workflowFacade.findAllWorkflows();
        Map<String, Workflow> map = new LinkedHashMap<String, Workflow>();

        for (Workflow workflow : original) {
            map.put(workflow.getName(), workflow);
        }

        return map;
    }

    public Map<String, WorkflowState> getWorkflowStates() {
        List<Workflow> original = workflowFacade.findAllWorkflows();
        Map<String, WorkflowState> map = new LinkedHashMap<String, WorkflowState>();

        for (Workflow workflow : original) {
            for (WorkflowState state : workflow.getStates()) {
                map.put(workflow.getName() + " >> " + state.getName(), state);
            }
        }

        return map;
    }

    /**
     * Gets a {@link Map} of available {@link WorkflowStateType}s.
     *
     * @return {@link Map} of available {@link WorkflowStateType}s
     */
    public Map<String, WorkflowStateType> getWorkflowStateTypes() {
        Map<String, WorkflowStateType> types = new LinkedHashMap<String, WorkflowStateType>();

        for (WorkflowStateType type : WorkflowStateType.values()) {
            types.put(i18n.getString("Generic_WORKFLOW_STATE_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link NewsItemField} user fields.
     *
     * @return {@link Map} of available {@link NewsItemField} user fields
     */
    public Map<String, NewsItemField> getNewsItemFields() {
        Map<String, NewsItemField> fields = new LinkedHashMap<String, NewsItemField>();

        for (NewsItemField field : NewsItemField.values()) {
            fields.put(i18n.getString("Generic_NEWS_ITEM_FIELD_" + field.name()), field);
        }

        return fields;
    }

    /**
     * Gets a {@link Map} of available {@link Privilege}s.
     *
     * @return {@link Map} of available {@link Privilege}s
     */
    public Map<String, Privilege> getPrivileges() {
        Map<String, Privilege> privileges = new LinkedHashMap<String, Privilege>();

        for (SystemPrivilege privilege : SystemPrivilege.values()) {
            String lbl = i18n.getString("Generic_" + privilege.getClass().getName() + "." + privilege.name());
            privileges.put(lbl, new Privilege(privilege));
        }

        return privileges;
    }

    /**
     * Gets a {@link Map} of available {@link OutletType}s.
     *
     * @return {@link Map} of available {@link OutletType}s
     */
    public Map<String, OutletType> getOutletTypes() {
        Map<String, OutletType> types = new LinkedHashMap<String, OutletType>();

        for (OutletType type : OutletType.values()) {
            types.put(i18n.getString("Generic_OUTLET_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link FeeType}s.
     *
     * @return {@link Map} of available {@link FeeType}s
     */
    public Map<String, FeeType> getFeeTypes() {
        Map<String, FeeType> types = new LinkedHashMap<String, FeeType>();

        for (FeeType type : FeeType.values()) {
            types.put(i18n.getString("Generic_FEE_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link EmploymentType}s.
     *
     * @return {@link Map} of available {@link EmploymentType}s
     */
    public Map<String, EmploymentType> getEmploymentTypes() {
        Map<String, EmploymentType> types
                = new LinkedHashMap<String, EmploymentType>();

        for (EmploymentType type : EmploymentType.values()) {
            types.put(i18n.getString("Generic_EMPLOYMENT_TYPE_" + type.name()), type);
        }

        return types;
    }

    /**
     * Gets a {@link Map} of available {@link EmploymentType}s.
     *
     * @return {@link Map} of available {@link EmploymentType}s
     */
    public Map<String, WorkflowStatePermission> getWorkflowStatePermissions() {
        Map<String, WorkflowStatePermission> types = new LinkedHashMap<String, WorkflowStatePermission>();

        for (WorkflowStatePermission permission : WorkflowStatePermission.values()) {
            types.put(i18n.getString("Generic_WORKFLOW_STATE_PERMISSION_" + permission.name()), permission);
        }

        return types;
    }

    /**
     * Gets the current year.
     *
     * @return Current year
     */
    public int getCurrentYear() {
        return java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
    }

    public Map<String, String> getHours() {
        Map<String, String> map = new LinkedHashMap<String, String>();

modules/converge-war/src/main/webapp/Dashboard.jspx
<?xml version="1.0" encoding="UTF-8"?>
<jsp:root version="2.0" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:c="http://java.sun.com/jstl/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:fn="http://java.sun.com/jsp/jstl/functions" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">

    <ui:composition template="/WEB-INF/facelets/templates/dashboard.xhtml">

        <ui:define name="title">
            <h:outputText value="#{i18n.dashboard_PAGE_TITLE}" />
        </ui:define>

        <ui:define name="leftColumn">
            <a4j:keepAlive beanName="dashboard" />
            <converge:upcomingEvents />
        </ui:define>

        <ui:define name="middleColumn">
            <converge:activityStreamModule />
        </ui:define>

        <ui:define name="rightColumn">
            <converge:userProfileModule id="modUserProfile" user="#{userSession.user}" />
            <converge:announcements />
        </ui:define>
    </ui:composition>
</jsp:root>

modules/converge-war/src/main/webapp/SearchByEdition.jspx
<?xml version="1.0" encoding="UTF-8"?>
<jsp:root version="2.0" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:c="http://java.sun.com/jstl/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:fn="http://java.sun.com/jsp/jstl/functions" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags" xmlns:v="http://converge.i2m.dk">

    <ui:composition template="/WEB-INF/facelets/templates/search.xhtml">
        <ui:define name="body">
            <a4j:keepAlive beanName="searchByEdition" />

            <a4j:outputPanel ajaxRendered="true">
                <v:message />
            </a4j:outputPanel>

            <h:form id="frmQuery">
                <a4j:status onstart="Richfaces.showModalPanel('mpLoading')" onstop="Richfaces.hideModalPanel('mpLoading')" />
                <converge:moduleHeader moduleTitle="#{i18n.Search_BROWSE_BY_EDITION}"  />
                <div class="moduleContent">
                    <h:panelGroup>
                        <h:outputText value="#{i18n.Search_BROWSE_BY_EDITION_OUTLET}" style="margin-right: 5px;" />
                        <h:selectOneMenu value="#{searchByEdition.selectedOutlet}"  style="margin-right: 5px;" converter="#{converters.outletConverter}">
                            <f:selectItems value="#{common.outlets}" />
                        </h:selectOneMenu>

                        <h:outputText value="#{i18n.Search_BROWSE_BY_EDITION_DATE}"  style="margin-right: 5px;" />
                        <rich:calendar id="calDate" value="#{searchByEdition.selectedDate}"  style="margin-right: 5px;" popup="true" timeZone="#{common.systemTimeZone}" datePattern="#{i18n.Generic_FORMAT_DATE}">
                        </rich:calendar>

                        <a4j:commandButton type="submit" styleClass="button dynamicButton" value="#{i18n.Search_SHOW}" actionListener="#{searchByEdition.onSearch}" reRender="frmPage,frmQuery" />
                    </h:panelGroup>
                </div>
            </h:form>

            <converge:moduleSpacer />

            <h:form id="frmPage">
                <h:panelGroup rendered="#{searchByEdition.showResults}">
                    <a4j:repeat value="#{searchByEdition.editions}" var="edition">
                        <div style="clear: both; padding-bottom: 12px;"></div>

                        <h2><h:outputText value="#{edition.publicationDate}" >
                                <f:convertDateTime pattern="#{i18n.Generic_FORMAT_TIME}" timeZone="#{common.systemTimeZone}" />
                            </h:outputText></h2>

                        <rich:dataTable id="dtEditionAssignments" value="#{edition.assignments}" var="assignment" styleClass="table" headerClass="tableHeader" rowClasses="odd, even" sortPriority="#{converge:createList('colPosition,colPriority')}">
                            <rich:column styleClass="columnIcon center #{rowStyle}" headerClass="subColumnIcon">
                                <f:facet name="header">
                                </f:facet>
                                <h:outputLink value="#{facesContext.externalContext.request.contextPath}/NewsItemArchive.xhtml" target="_blank" rendered="#{assignment.endState}">
                                    <f:param value="#{assignment.id}" name="id" />
                                    <h:graphicImage value="#{res.NEWS_ITEM_ICON}" rendered="#{!assignment.locked}" title="#{assignment.status}" alt="#{assignment.status}"  />
                                    <h:graphicImage value="#{res.LOCK_ICON}" rendered="#{assignment.locked}" />
                                </h:outputLink>
                                <h:graphicImage value="#{res.NEWS_ITEM_ICON}" title="#{assignment.status}" alt="#{assignment.status}" rendered="#{!assignment.endState}" />
                                <rich:toolTip styleClass="lockTooltip" rendered="#{assignment.locked}">

                                    <h:outputFormat value="#{i18n.Search_LOCKED_TOOLTIP}" escape="false">
                                        <f:param value="#{assignment.checkedOutBy}" />
                                        <f:param value="#{assignment.checkedOut}" />
                                    </h:outputFormat>
                                </rich:toolTip>
                            </rich:column>

                            <rich:column sortBy="#{assignment.id}" styleClass="right columnId" headerClass="columnId">
                                <f:facet name="header">
                                    <h:outputText value="#{i18n.SearchByEdition_NEWS_ITEM_ID}" title="#{i18n.Search_ARTICLE_ID_TOOLTIP}" />
                                </f:facet>
                                <h:outputLink value="#{facesContext.externalContext.request.contextPath}/NewsItemArchive.xhtml" target="_blank" rendered="#{assignment.endState}">
                                    <f:param value="#{assignment.id}" name="id" />
                                    <h:outputText value="#{assignment.id}">
                                        <f:convertNumber integerOnly="true" type="number" pattern="#{i18n.Generic_FORMAT_ID}" />
                                    </h:outputText>
                                </h:outputLink>
                                <h:outputText value="#{assignment.id}" rendered="#{!assignment.endState}">
                                    <f:convertNumber integerOnly="true" type="number" pattern="#{i18n.Generic_FORMAT_ID}" />
                                </h:outputText>
                            </rich:column>

                            <rich:column sortBy="#{assignment.title}" styleClass="left">
                                <f:facet name="header">
                                    <h:outputText value="#{i18n.Search_NEWSITEM_HEADLINE}" />
                                </f:facet>
                                <h:outputLink value="#{facesContext.externalContext.request.contextPath}/NewsItemArchive.xhtml" target="_blank" rendered="#{assignment.endState}">
                                    <f:param value="#{assignment.id}" name="id" />
                                    <h:outputText value="#{assignment.title}" />
                                </h:outputLink>
                                <h:outputText value="#{assignment.title}" rendered="#{!assignment.endState}" />
                            </rich:column>

                            <rich:column sortBy="#{assignment.section}" styleClass="left columnMediumNumber">
                                <f:facet name="header">
                                    <h:outputText value="#{i18n.Search_NEWSITEM_SECTION}" />
                                </f:facet>
                                <h:outputText value="#{assignment.section}" />
                            </rich:column>

                            <rich:column sortBy="#{assignment.wordCount}" styleClass="columnSmallNumber">
                                <f:facet name="header">
                                    <h:outputText value="#{i18n.Search_NEWSITEM_WORD_COUNT}" />
                                </f:facet>
                                <h:outputText value="#{assignment.wordCount} (#{assignment.targetWordCount})" rendered="#{assignment.targetWordCount != 0}" />
                                <h:outputText value="#{assignment.wordCount}" rendered="#{assignment.targetWordCount == 0}" />
                            </rich:column>

                            <rich:column id="colPosition" sortBy="#{assignment.start}" sortOrder="ASCENDING" styleClass="columnSmallNumber">
                                <f:facet name="header">
                                    <h:outputText value="#{i18n.Search_NEWSITEM_START}" />
                                </f:facet>
                                <h:outputText value="#{assignment.start}" />
                            </rich:column>

                            <rich:column id="colPriority" sortBy="#{assignment.position}" sortOrder="ASCENDING" styleClass="columnSmallNumber">
                                <f:facet name="header">
                                    <h:outputText value="#{i18n.Search_NEWSITEM_POSITION}" />
                                </f:facet>
                                <h:outputText value="#{assignment.position}" />
                            </rich:column>
                        </rich:dataTable>
                    </a4j:repeat>

                </h:panelGroup>
            </h:form>
        </ui:define>

    </ui:composition>
</jsp:root>

modules/converge-war/src/main/webapp/SessionExpired.jsp
<%
    response.setContentType("text/xml;charset=UTF-8");
    response.setStatus(200);
    response.sendRedirect(request.getContextPath() + "/Dashboard.xhtml");
%>

modules/converge-war/src/main/webapp/logout.jsp
<%@page contentType="text/html" pageEncoding="utf-8"%><%
request.getSession().invalidate();
(new com.sun.appserv.security.ProgrammaticLogin()).logout(request, response, true);
response.sendRedirect(request.getContextPath());
%>