modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/BaseBean.java
/*
 * Copyright (C) 2010 Interactive Media Management
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.DataNotFoundException;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.ejb.facades.UserFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;

/**
 * Base bean providing useful methods for JSF managed beans.
 *
 * @author Allan Lykke Christensen
 */
public abstract class BaseBean {

    protected static final Logger LOG = Logger.getLogger(BaseBean.class.getName());

    @EJB private UserFacadeLocal userFacade;

    private UserAccount currentUserAccount;

    /**
     * Gets the current user, or {@code null} if the user is not logged in.
     *
     * @return Current user logged in.
     */
    public UserAccount getUser() {
        if (currentUserAccount == null) {
            FacesContext ctx = FacesContext.getCurrentInstance();
            String uid = ctx.getExternalContext().getRemoteUser();

            // Used by the session overview to see the name of the users logged in
            JsfUtils.getHttpSession().setAttribute("uid", uid);

            if (uid != null || !uid.isEmpty()) {
                try {
                    currentUserAccount = userFacade.findById(uid);
                } catch (DataNotFoundException ex) {
                    LOG.log(Level.INFO, "User [{0}] could not be found", uid);
                }
            }

        }
        return currentUserAccount;
    }

    /**
     * Determines if the current user is in a given role.
     *
     * @param role
     *          Name of the role
     * @return <code>true</code> if the user is in the given role, otherwise
     *         <code>false</code>
     */
    public boolean isUserInRole(String role) {
        FacesContext ctx = FacesContext.getCurrentInstance();
        return ctx.getExternalContext().isUserInRole(role);
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Bundle.java
/*
 * Copyright (C) 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

/**
 * Identifier of {@link java.util.ResourceBundle}s available in
 * {@code FacesContext.xml}.
 *
 * @author Allan Lykke Christensen
 */
public enum Bundle {

    /**
     * Old ResourceBundle containing messages.
     *
     * @deprecated Use {@link Bundle#i18n}
     */
    msgs,
    /**
     * Old ResourceBundle containing resources.
     *
     * @deprecated Use {@link Bundle#i18n}
     */
    res,
    /**
     * ResourceBundle containing messages and resources for the web application.
     */
    i18n;
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Converters.java
/*
 *  Copyright (C) 2010 - 2011 Interactive Media Management
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.workflow.Department;
import dk.i2m.converge.core.workflow.Edition;
import dk.i2m.converge.ejb.services.NewswireServiceLocal;
import dk.i2m.converge.jsf.converters.UserRoleConverter;
import dk.i2m.converge.jsf.converters.WorkflowConverter;
import dk.i2m.converge.jsf.converters.WorkflowStateConverter;
import dk.i2m.converge.core.workflow.Outlet;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.core.security.UserRole;
import dk.i2m.converge.core.calendar.EventCategory;
import dk.i2m.converge.core.metadata.Concept;
import dk.i2m.converge.core.workflow.Workflow;
import dk.i2m.converge.core.workflow.WorkflowState;
import dk.i2m.converge.core.workflow.WorkflowStep;
import dk.i2m.converge.ejb.facades.CalendarFacadeLocal;
import dk.i2m.converge.ejb.facades.ListingFacadeLocal;
import dk.i2m.converge.ejb.facades.CatalogueFacadeLocal;
import dk.i2m.converge.ejb.facades.MetaDataFacadeLocal;
import dk.i2m.converge.ejb.facades.OutletFacadeLocal;
import dk.i2m.converge.ejb.facades.SystemFacadeLocal;
import dk.i2m.converge.ejb.facades.UserFacadeLocal;
import dk.i2m.converge.ejb.facades.WorkflowFacadeLocal;
import dk.i2m.converge.jsf.converters.ClassConverter;
import dk.i2m.converge.jsf.converters.ConceptConverter;
import dk.i2m.converge.jsf.converters.CurrencyConverter;
import dk.i2m.converge.jsf.converters.DepartmentConverter;
import dk.i2m.converge.jsf.converters.EditionCandidateConverter;
import dk.i2m.converge.jsf.converters.EditionConverter;
import dk.i2m.converge.jsf.converters.NewsItemFieldConverter;
import dk.i2m.converge.jsf.converters.EventCategoryConverter;
import dk.i2m.converge.jsf.converters.FinancialMarketConverter;
import dk.i2m.converge.jsf.converters.LanguageConverter;
import dk.i2m.converge.jsf.converters.LocaleConverter;
import dk.i2m.converge.jsf.converters.RenditionConverter;
import dk.i2m.converge.jsf.converters.CatalogueConverter;
import dk.i2m.converge.jsf.converters.NewswireServiceConverter;
import dk.i2m.converge.jsf.converters.OutletConverter;
import dk.i2m.converge.jsf.converters.SectionConverter;
import dk.i2m.converge.jsf.converters.SystemPrivilegeConverter;
import dk.i2m.converge.jsf.converters.UserAccountConverter;
import dk.i2m.converge.jsf.converters.WeatherLocationConverter;
import dk.i2m.converge.jsf.converters.WeatherSituationConverter;
import dk.i2m.converge.jsf.converters.WorkflowStepConverter;
import dk.i2m.jsf.converters.EnumTypeConverter;
import java.util.Locale;
import javax.ejb.EJB;
import javax.faces.convert.Converter;

/**
 * Managed bean with access to JSF converters.
 *
 * @author Allan Lykke Christensen
 */
public class Converters {

    @EJB private OutletFacadeLocal outletFacade;

    @EJB private WorkflowFacadeLocal workflowFacade;

    @EJB private UserFacadeLocal userFacade;

    @EJB private MetaDataFacadeLocal metaDataFacade;

    @EJB private CalendarFacadeLocal calendarFacade;

    @EJB private CatalogueFacadeLocal catalogueFacade;

    @EJB private SystemFacadeLocal systemFacade;

    @EJB private ListingFacadeLocal listingFacade;

    @EJB private NewswireServiceLocal newswireService;

    /**
     * Gets an instance of the {@link SystemPrivilegeConverter}.
     *
     * @return Instance of the {@link SystemPrivilegeConverter}.
     */
    public Converter getSystemPrivilegeConverter() {
        return new SystemPrivilegeConverter(userFacade);
    }

    /**
     * Gets the {@link Converter} for {@link Outlet} objects.
     *
     * @return {@link Converter} for {@link Outlet} objects
     */
    public Converter getOutletConverter() {
        return new OutletConverter(outletFacade);
    }

    public Converter getWeatherLocationConverter() {
        return new WeatherLocationConverter(listingFacade);
    }

    public Converter getWeatherSituationConverter() {
        return new WeatherSituationConverter(listingFacade);
    }

    public Converter getCurrencyConverter() {
        return new CurrencyConverter(listingFacade);
    }

    public Converter getFinancialMarketConverter() {
        return new FinancialMarketConverter(listingFacade);
    }

    /**
     * Gets a {@link Converter} for {@link Concept} objects.
     *
     * @return {@link Converter} for {@link Concept} objects
     */
    public Converter getConceptConverter() {
        return new ConceptConverter(metaDataFacade);
    }

    /**
     * Gets a {@link Converter} for {@link WorkflowState} objects.
     *
     * @return {@link Converter} for {@link WorkflowState} objects
     */
    public Converter getWorkflowStateConverter() {
        return new WorkflowStateConverter(workflowFacade);
    }

    /**
     * Gets a {@link Converter} for {@link WorkflowStep} objects.
     *
     * @return {@link Converter} for {@link WorkflowStep} objects
     */
    public Converter getWorkflowStepConverter() {
        return new WorkflowStepConverter(workflowFacade);
    }

    /**
     * Gets a {@link Converter} for {@link Workflow} objects.
     *
     * @return {@link Converter} for {@link Workflow} objects
     */
    public Converter getWorkflowConverter() {
        return new WorkflowConverter(workflowFacade);
    }

    /**
     * Gets a {@link Converter} for {@link UserRole} objects.
     *
     * @return {@link Converter} for {@link UserRole} objects
     */
    public Converter getUserRoleConverter() {
        return new UserRoleConverter(userFacade);
    }

    /**
     * Gets a {@link Converter} for {@link UserAccount} objects.
     *
     * @return {@link Converter} for {@link UserAccount} objects
     */
    public Converter getUserAccountConverter() {
        return new UserAccountConverter(userFacade);
    }

    /**
     * Gets a {@link Converter} for {@link Department} objects.
     *
     * @return {@link Converter} for {@link Department} objects
     */
    public Converter getDepartmentConverter() {
        return new DepartmentConverter(outletFacade);
    }

    /**
     * Gets a {@link Converter} for enumerations.
     *
     * @return {@link Converter} for enumerations
     */
    public Converter getEnumTypeConverter() {
        return new EnumTypeConverter();
    }

    /**
     * Gets a {@link Converter} for NewsItemFields
     *
     * @return {@link Converter} for NewsItemFields
     */
    public Converter getNewsItemFieldConverter() {
        return new NewsItemFieldConverter();
    }

    /**
     * Gets a {@link Converter} for {@link EventCategory} objects.
     *
     * @return {@link Converter} for {@link EventCategory} objects
     */
    public Converter getEventCategoryConverter() {
        return new EventCategoryConverter(calendarFacade);
    }

    /**
     * Gets a {@link Converter} for {@link Locale} objects.
     *
     * @return {@link Converter} for {@link Locale} objects
     */
    public Converter getLocaleConverter() {
        return new LocaleConverter();
    }

    /**
     * Gets a {@link Converter} for {@link Edition} objects.
     *
     * @return {@link Converter} for {@link Edition} objects
     */
    public Converter getEditionConverter() {
        return new EditionConverter(outletFacade);
    }

    /**
     * Gets a {@link Converter} for {@link Section} objects.
     *
     * @return {@link Converter} for {@link Section} objects
     */
    public Converter getSectionConverter() {
        return new SectionConverter(outletFacade);
    }

    /**
     * Gets a {@link Conveter} for {@link Class}es.
     *
     * @return {@link Conveter} for {@link Class}es.
     */
    public Converter getClassConverter() {
        return new ClassConverter();
    }

    public Converter getEditionCandidateConverter() {
        return new EditionCandidateConverter();
    }

    /**
     * Gets a {@link Converter} for media repositories.
     *
     * @return {@link Converter} for media repositories
     */
    public Converter getMediaRepositoryConverter() {
        return new CatalogueConverter(catalogueFacade);
    }

    
    /**
     * Gets a {@link Converter} for {@link Rendition}s.
     * 
     * @return JSF {@link Converter} for {@link Rendition}s
     */
    public Converter getRenditionConverter() {
        return new RenditionConverter(catalogueFacade);
    }

    public Converter getLanguageConverter() {
        return new LanguageConverter(systemFacade);
    }

    public Converter getNewswireServiceConverter() {
        return new NewswireServiceConverter(newswireService);
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Dashboard.java
/*
 *  Copyright (C) 2010 - 2011 Interactive Media Management
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

import dk.i2m.converge.core.calendar.Event;
import dk.i2m.converge.core.security.UserAccount;
import dk.i2m.converge.core.views.CurrentAssignment;
import dk.i2m.converge.ejb.facades.CalendarFacadeLocal;
import dk.i2m.converge.ejb.facades.NewsItemFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 * Backing bean for {@code /Dashboard.jspx}.
 *
 * @author Allan Lykke Christensen
 */
public class Dashboard {

    @EJB private CalendarFacadeLocal calendarFacade;

    @EJB private NewsItemFacadeLocal newsItemFacade;

    private DataModel events = null;

    private DataModel assignments = null;

    private DataModel news = null;

    /**
     * Gets the {@link DataModel} containing the user assignments.
     *
     * @return {@link DataModel} containing the user assignments
     */
    public DataModel getUserAssignments() {
        if (this.assignments == null) {
            List<CurrentAssignment> ni = newsItemFacade.findCurrentAssignments(getUserAccount().getUsername());
            this.assignments = new ListDataModel(ni);
        }

        return this.assignments;
    }

    /**
     * Gets the {@link DataModel} containing upcoming events.
     *
     * @return {@link DataModel} containing upcoming events
     */
    public DataModel getEvents() {
        if (this.events == null) {
            List<Event> upcomingEvent = calendarFacade.findUpcomingEvents(5);
            this.events = new ListDataModel(upcomingEvent);
        }
        return this.events;
    }

    private UserAccount getUserAccount() {
        final String valueExpression = "#{userSession.user}";
        return (UserAccount) JsfUtils.getValueOfValueExpression(valueExpression);
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/Help.java
/*
 *  Copyright (C) 2010 Interactive Media Management
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans;

/**
 * JSF managed bean for the {@code /Help.jspx} page.
 *
 * @author Allan Lykke Christensen
 */
public class Help {

    private String title = "Getting Help";

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}

modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/currentAssignmentsModule.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">
    <h:form id="frmMyAssignments">
        <converge:moduleHeader moduleTitle="#{i18n.currentAssignmentsModule_TITLE}" />
        <div class="moduleContent">
            <h:panelGrid columns="2">
                <h:graphicImage value="#{res.NEWS_ITEM_ICON}" />
                <h:outputLink value="#{facesContext.externalContext.request.contextPath}/Inbox.xhtml">
                    <h:outputFormat value="#{i18n.currentAssignmentsModule_X_ASSIGNMENTS_IN_INBOX}">
                        <f:param value="#{dashboard.userAssignments.rowCount}" />
                    </h:outputFormat>
                </h:outputLink>
            </h:panelGrid>
        </div>
    </h:form>
    <converge:moduleSpacer />
</ui:composition>

modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/loadingMessage.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich">
    <a4j:status id="staLoadingMessage#{id}"
                for="#{for}" 
                onstart="Richfaces.showModalPanel('mpLoadingMessage#{id}')"
                onstop="Richfaces.hideModalPanel('mpLoadingMessage#{id}')" />

    <rich:modalPanel id="mpLoadingMessage#{id}" autosized="true" resizeable="false" minHeight="50" minWidth="300" zindex="2000" >
        <h:panelGrid styleClass="pleaseWaitBackground">
            <h:outputText value="#{message}" styleClass="pleaseWaitMessage" />
            <h:outputText value="&#160;" />
            <h:outputText value="&#160;" />
            <h:outputText value="&#160;" />
            <h:outputText value="&#160;" />
        </h:panelGrid>
    </rich:modalPanel>
</ui:composition>

modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/newsItemModuleActors.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">

    <converge:moduleHeader moduleTitle="#{msgs.newsitem_ACTORS}" />
    <div>
        <rich:dataTable id="dtNewsItemActors" var="actor" value="#{value.selectedNewsItem.actors}" columnClasses="left, left" rowClasses="odd, even" style="width: 96%; margin-left: 2%; margin-right: 2%;  border: 0px;">
            <rich:column style="width: 37px;  border: 0px;">
                <h:graphicImage styleClass="profilePhoto" value="/UserPhoto?uid=#{actor.user.id}" alt="#{actor.user.fullName}" title="#{actor.user.fullName}" height="32" width="32" />
            </rich:column>
            <rich:column style="border: 0px;">
                <h:panelGrid>
                    <h:outputText value="#{actor.user.fullName}" style="font-weight: bold; font-size: 11px;" title="#{actor.user.fullName}">
                        <f:converter converterId="i2m.abbreviationDisplay" />
                        <f:attribute name="maxLength" value="19" />
                    </h:outputText>
                    <h:outputText value="#{actor.role.name}" style="font-size: 10px;" />
                </h:panelGrid>
            </rich:column>
        </rich:dataTable>
        <c:if test="#{value.currentActor &amp;&amp; !value.readOnly}">
            <div style="width: 100%; text-align: center;">
                <a4j:commandLink ajaxSingle="true" actionListener="#{value.onActorSelect}" reRender="mpActorSelect">
                    <h:outputText value="#{msgs.newsitem_ADD_REMOVE}" />
                    <rich:componentControl for="mpActorSelect" operation="show" event="oncomplete" />
                </a4j:commandLink>
            </div>
        </c:if>
    </div>

    <a4j:region id="regActorSelect">



        <rich:modalPanel id="mpActorSelect" autosized="true" domElementAttachment="parent" rendered="#{value.currentActor}">
            <f:facet name="header">
                <h:panelGroup>
                    <h:outputText value="#{msgs.newsitem_ACTORS}"></h:outputText>
                </h:panelGroup>
            </f:facet>
            <f:facet name="controls">
                <h:panelGroup>
                    <h:graphicImage id="imgCloseActorSelect" value="#{i18n.resource_ICON_DIALOGUE_CLOSE}" style="link" />
                    <rich:componentControl for="mpActorSelect" attachTo="imgCloseActorSelect" operation="hide" event="onclick"/>
                </h:panelGroup>
            </f:facet>

            <h:panelGrid style="width: 480px;">

                <rich:tabPanel id="tpActorSelect" switchType="client" activeTabClass="tabActive" inactiveTabClass="tabInactive">

                    <rich:tab label="#{msgs.newsitem_ACTORS}">
                        <h:panelGrid columnClasses="tabSheet" style="padding: 10px; width: 100%">

                            <rich:dataTable id="dtActorEdit" var="actor" value="#{value.selectedNewsItem.actors}" styleClass="table" rowClasses="odd, even" style="width: 100%">

                                <rich:column>
                                    <h:outputText value="#{actor.role.name}" />
                                </rich:column>

                                <rich:column>
                                    <h:outputText value="#{actor.user.fullName}" />
                                </rich:column>

                                <rich:column styleClass="columnIcon center">
                                    <a4j:commandLink onclick="if (confirm('#{msgs.newsitem_REMOVE_ACTOR_PROMPT}') != true){ return false; };" ajaxSingle="true" reRender="dtActorEdit, dtNewsItemActors">
                                        <f:setPropertyActionListener value="#{actor}" target="#{value.deleteActor}" />
                                        <h:graphicImage alt="#{msgs.DELETE}" title="#{msgs.DELETE}" value="#{i18n.resource_ICON_DELETE}"/>
                                    </a4j:commandLink>
                                </rich:column>
                            </rich:dataTable>

                            <h:outputText value="New Actor" style="font-weight: bold" />
                            <h:panelGrid columns="3">
                                <h:outputText value="Role" />
                                <h:outputText value="User" />
                                <h:outputText value="" />
                                <h:selectOneMenu id="somNewActorRole" value="#{value.newActor.role}" converter="#{converters.userRoleConverter}">
                                    <f:selectItem itemLabel="- Select Role -" />
                                    <f:selectItems value="#{value.outletRoles}" />
                                    <a4j:support event="onchange" reRender="somNewActorUser" />
                                </h:selectOneMenu>

                                <h:selectOneMenu id="somNewActorUser" value="#{value.newActor.user}" converter="#{converters.userAccountConverter}">
                                    <f:selectItem itemLabel="- Select User -" />
                                    <f:selectItems value="#{value.roleUsers}" />
                                </h:selectOneMenu>

                                <a4j:status>
                                    <f:facet name="start">
                                        <a4j:commandButton disabled="true" value="#{msgs.ADD}" styleClass="button dynamicButton" actionListener="#{value.onAddActor}" reRender="somNewActorRole, somNewActorUser, dtActorEdit, dtNewsItemActors" />
                                    </f:facet>
                                    <f:facet name="stop">
                                        <a4j:commandButton value="#{msgs.ADD}" styleClass="button dynamicButton" actionListener="#{value.onAddActor}" reRender="somNewActorRole, somNewActorUser, dtActorEdit, dtNewsItemActors" />
                                    </f:facet>
                                </a4j:status>

                            </h:panelGrid>

                        </h:panelGrid>
                    </rich:tab>
                </rich:tabPanel>

                <h:panelGroup styleClass="dialogueButtons">
                    <h:commandLink id="lnkCancelActorSelect" styleClass="dialogButton" value="#{msgs.CLOSE}" onclick="#{rich:component('mpActorSelect')}.hide(); return false;" />
                </h:panelGroup>

            </h:panelGrid>

        </rich:modalPanel>
    </a4j:region>

    <div style="clear: both; padding-bottom: 12px;"></div>

</ui:composition>

modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/newsItemModuleBrief.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">

    <c:if test="#{newsItem.fieldVisible['BRIEF']}">
        <converge:moduleHeader moduleTitle="#{msgs.newsitem_BRIEF}" />
        <div class="moduleContent">
            <h:inputTextarea id="txtNewsItemBrief" value="#{newsItem.selectedNewsItem.brief}" style="width: 98%; height: 100px; margin-left: 1%; margin-right: 1%" styleClass="text mediumInput" disabled="#{!value.currentActor || value.readOnly}" />
        </div>
        <converge:moduleSpacer />
    </c:if>

</ui:composition>

modules/converge-war/src/main/webapp/WEB-INF/facelets/taglib/converge/newsItemModuleByLine.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jstl/core" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich" xmlns:converge="http://com.interactivemediamanagement.converge/tags">

    <c:if test="#{newsItem.fieldVisible['BY_LINE']}">
        <converge:moduleHeader moduleTitle="#{msgs.newsitem_BY_LINE}" />
        <div class="moduleContent">
            <h:inputText id="txtNewsItemByLine" maxlength="255" value="#{value.selectedNewsItem.byLine}" style="width: 98%; margin-left: 1%; margin-right: 1%;" styleClass="text" disabled="#{!value.currentActor || value.readOnly}" />
        </div>
        <div style="clear: both; padding-bottom: 12px;"></div>
    </c:if>
    
</ui:composition>