modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/administrator/Administration.java
/*
 * Copyright (C) 2010 - 2011 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans.administrator;

import java.lang.management.ManagementFactory;
import java.lang.management.RuntimeMXBean;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * Backing bean for {@code /administrator/Administration.jspx}.
 *
 * @author Allan Lykke Christensen
 */
public class Administration {

    private RuntimeMXBean mx = ManagementFactory.getRuntimeMXBean();

    /**
     * Creates a new instance of {@link Administration}.
     */
    public Administration() {
    }

    public long getTotalMemory() {
        return Runtime.getRuntime().totalMemory();
    }

    public long getUsedMemory() {
        return getTotalMemory() - getFreeMemory();
    }

    public long getMaxMemory() {
        return Runtime.getRuntime().maxMemory();
    }

    public long getFreeMemory() {
        return Runtime.getRuntime().freeMemory();
    }

    public String getOperatingSystem() {
        return System.getProperty("os.name") + " (" + System.getProperty("os.arch") + ") " + System.getProperty("os.version");
    }

    public String getJavaVersion() {
        return System.getProperty("java.vm.name") + " " + System.getProperty("java.vm.version") + " (" + System.getProperty("java.vm.vendor") + ")";
    }

    public String getBootClassPath() {
        return mx.getBootClassPath();
    }

    public String getClassPath() {
        return mx.getClassPath();
    }

    public List<String> getCommandLineArguments() {
        return mx.getInputArguments();
    }

    public Map<String, String> getSystemProperties() {
        return mx.getSystemProperties();
    }

    public Date getStartTime() {
        return new Date(mx.getStartTime());
    }

    /**
     * Gets the up time of the virtual machine in milliseconds.
     * 
     * @return Up time of the VM in ms.
     */
    public long getUpTime() {
        return mx.getUptime();
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/administrator/Announcements.java
/*
 *  Copyright (C) 2010 Interactive Media Management
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans.administrator;

import dk.i2m.converge.core.Announcement;
import dk.i2m.converge.ejb.facades.SystemFacadeLocal;
import java.util.Calendar;
import javax.ejb.EJB;
import javax.faces.event.ActionEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 * Backing bean for {@code /administrator/Announcements.jspx}.
 *
 * @author Allan Lykke Christensen
 */
public class Announcements {

    @EJB private SystemFacadeLocal systemFacade;

    private DataModel announcements = null;

    private Announcement selectedAnnouncement = null;

    public void onNew(ActionEvent event) {
        selectedAnnouncement = new Announcement();
        selectedAnnouncement.setPublished(true);
        selectedAnnouncement.setDate(Calendar.getInstance());
        selectedAnnouncement.setThumb("/images/announcement/megaphone.png");
    }

    public void onSave(ActionEvent event) {
        if (isEditMode()) {
            selectedAnnouncement = systemFacade.updateAnnouncement(selectedAnnouncement);
        } else {
            selectedAnnouncement = systemFacade.createAnnouncement(selectedAnnouncement);
        }
        announcements = null;
    }

    public void onDelete(ActionEvent event) {
        if (isEditMode()) {
            systemFacade.deleteAnnouncement(selectedAnnouncement.getId());
        }
        announcements = null;
    }

    public boolean isEditMode() {
        if (selectedAnnouncement != null && selectedAnnouncement.getId() != null) {
            return true;
        } else {
            return false;
        }
    }

    public DataModel getAnnouncements() {
        if (announcements == null) {
            announcements = new ListDataModel(systemFacade.getAnnouncements());
        }
        return announcements;
    }

    public Announcement getSelectedAnnouncement() {
        return selectedAnnouncement;
    }

    public void setSelectedAnnouncement(Announcement selectedAnnouncement) {
        this.selectedAnnouncement = selectedAnnouncement;
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/administrator/CalendarCategories.java
/*
 *  Copyright (C) 2010 - 2012 Interactive Media Management
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans.administrator;

import dk.i2m.converge.core.calendar.EventCategory;
import dk.i2m.converge.ejb.facades.CalendarFacadeLocal;
import dk.i2m.converge.jsf.beans.Bundle;
import dk.i2m.jsf.JsfUtils;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.event.ActionEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 * Backing bean for {@code /administrator/CalendarCategories.jspx}.
 *
 * @author Allan Lykke Christensen
 */
public class CalendarCategories {

    @EJB private CalendarFacadeLocal calendarFacade;

    private DataModel categories = null;

    private EventCategory selectedCategory;

    public void onSave(ActionEvent event) {
        if (event.getComponent().getId().equalsIgnoreCase("lnkSaveEventCategoryDetails")) {
            selectedCategory = calendarFacade.create(selectedCategory);
            JsfUtils.createMessage("frmEventCategories", 
                    FacesMessage.SEVERITY_INFO, Bundle.i18n.name(), 
                    "administrator_CalendarCategories_EVENT_CATEGORY_CREATED");
        } else {
            selectedCategory = calendarFacade.update(selectedCategory);
            JsfUtils.createMessage("frmEventCategories", 
                    FacesMessage.SEVERITY_INFO, Bundle.i18n.name(), 
                    "administrator_CalendarCategories_EVENT_CATEGORY_UPDATED");
        }
        categories = null;
    }

    public void onNew(ActionEvent event) {
        selectedCategory = new EventCategory();
    }

    public void onDelete(ActionEvent event) {
        if (selectedCategory != null) {
            calendarFacade.deleteEventCategory(selectedCategory.getId());
        }
        categories = null;
    }

    public DataModel getCategories() {
        if (categories == null) {
            categories = new ListDataModel(calendarFacade.findAllCategories());
        }
        return categories;
    }

    public EventCategory getSelectedCategory() {
        return selectedCategory;
    }

    public void setSelectedCategory(EventCategory selectedCategory) {
        this.selectedCategory = selectedCategory;
    }

    public boolean isEditMode() {
        if (selectedCategory == null || selectedCategory.getId() == null) {
            return false;
        } else {
            return true;
        }
    }

    public boolean isAddMode() {
        return !isEditMode();
    }

}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/administrator/Configuration.java
/*
 * Copyright (C) 2010 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans.administrator;

import dk.i2m.converge.core.plugin.Plugin;
import dk.i2m.converge.domain.Property;
import dk.i2m.converge.ejb.facades.SystemFacadeLocal;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.event.ActionEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 * Backing bean for <code>/administrator/Configuration.jspx</code>.
 *
 * @author Allan Lykke Christensen
 */
public class Configuration {

    @EJB private SystemFacadeLocal systemFacade;

    private DataModel plugins = null;

    private DataModel properties = null;

    /**
     * Creates a new instance of {@link Configuration}.
     */
    public Configuration() {
    }

    /**
     * Event handler for updating all the properties in the {@link DataModel}.
     * 
     * @param event
     *          Event that invoked the handler
     */
    public void onUpdateProperties(ActionEvent event) {
        List<Property> propertyList = (List<Property>) this.properties.getWrappedData();
        systemFacade.updateSystemProperties(propertyList);
        this.properties = null;
    }


    /**
     * Gets a {@link DataModel} of the installed plugins.
     *
     * @return {@link DataModel} of installed plugins
     */
    public DataModel getPlugins() {
        if (this.plugins == null) {
            List<Plugin> p = new ArrayList<Plugin>();
            for (String key : systemFacade.getPlugins().keySet()) {
                p.add(systemFacade.getPlugins().get(key));
            }
            this.plugins = new ListDataModel(p);
        }
        return this.plugins;
    }

    /**
     * Gets a {@link DataModel} of system properties.
     *
     * @return {@link DataModel} of system properties
     */
    public DataModel getProperties() {
        if (this.properties == null) {
            this.properties = new ListDataModel(systemFacade.getSystemProperties());
        }
        return this.properties;
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/administrator/Languages.java
/*
 *  Copyright (C) 2010 Interactive Media Management
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans.administrator;

import dk.i2m.converge.core.content.Language;
import dk.i2m.converge.ejb.facades.ReferentialIntegrityException;
import dk.i2m.converge.ejb.facades.SystemFacadeLocal;
import dk.i2m.jsf.JsfUtils;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.event.ActionEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 * Backing bean for {@code /administrator/Languages.jspx}.
 *
 * @author Allan Lykke Christensen
 */
public class Languages {

    @EJB private SystemFacadeLocal systemFacade;

    private DataModel languages = null;

    private Language selectedLanguage = null;

    public Languages() {
    }

    public void onNew(ActionEvent event) {
        selectedLanguage = new Language();
    }

    public void onSave(ActionEvent event) {
        if (isEditMode()) {
            selectedLanguage = systemFacade.updateLanguage(selectedLanguage);
            JsfUtils.createMessage("frmPage", FacesMessage.SEVERITY_INFO, "language_CREATED", selectedLanguage.getName());
        } else {
            selectedLanguage = systemFacade.createLanguage(selectedLanguage);
            JsfUtils.createMessage("frmPage", FacesMessage.SEVERITY_INFO, "language_UPDATED", selectedLanguage.getName());
        }
        languages = null;
    }

    public void onDelete(ActionEvent event) {
        if (isEditMode()) {
            try {
                systemFacade.deleteLanguage(selectedLanguage.getId());
            } catch (ReferentialIntegrityException ex) {
                JsfUtils.createMessage("frmPage", FacesMessage.SEVERITY_ERROR, "language_LANGUAGE_IN_USE", selectedLanguage.getName());
            }
        }
        languages = null;
    }

    public DataModel getLanguages() {
        if (languages == null) {
            this.languages = new ListDataModel(systemFacade.getLanguages());
        }
        return languages;
    }

    public void setLanguages(DataModel languages) {
        this.languages = languages;
    }

    public Language getSelectedLanguage() {
        return selectedLanguage;
    }

    public void setSelectedLanguage(Language selectedLanguage) {
        this.selectedLanguage = selectedLanguage;
    }

    public boolean isEditMode() {
        if (selectedLanguage == null || selectedLanguage.getId() == null) {
            return false;
        } else {
            return true;
        }
    }
}

modules/converge-war/src/main/java/dk/i2m/converge/jsf/beans/administrator/Log.java
/*
 * Copyright (C) 2011 - 2012 Interactive Media Management
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dk.i2m.converge.jsf.beans.administrator;

import dk.i2m.converge.ejb.facades.SystemFacadeLocal;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.event.ActionEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 * Backing bean for {@code /administrator/Log.jspx}.
 *
 * @author Allan Lykke Christensen
 */
public class Log {

    @EJB private SystemFacadeLocal systemFacade;

    private DataModel logEntries = new ListDataModel();

    /**
     * Creates a new instance of {@link Log}.
     */
    public Log() {
    }

    /**
     * Event handler invoked after construction of the page.
     */
    @PostConstruct
    public void onInit() {
        onRefresh(null);
    }

    /**
     * Event handler for updating the log listing.
     * <p/>
     * @param event Event that invoked the handler
     */
    public void onRefresh(ActionEvent event) {
        logEntries = new ListDataModel(systemFacade.findLogEntries(0, 2000));
    }

    /**
     * Gets the log listing.
     * <p/>
     * @return {@link DataModel} containing the log listing
     */
    public DataModel getLogEntries() {
        return logEntries;
    }
}

modules/converge-war/src/main/webapp/administrator/CalendarCategories.jspx
<?xml version='1.0' encoding='UTF-8' ?>
<jsp:root version="2.0"
          xmlns:html="http://www.w3.org/1999/xhtml"
          xmlns:jsp="http://java.sun.com/JSP/Page"
          xmlns:c="http://java.sun.com/jstl/core"
          xmlns:ui="http://java.sun.com/jsf/facelets"
          xmlns:h="http://java.sun.com/jsf/html"
          xmlns:f="http://java.sun.com/jsf/core"
          xmlns:fn="http://java.sun.com/jsp/jstl/functions"
          xmlns:a4j="http://richfaces.org/a4j"
          xmlns:rich="http://richfaces.org/rich"
          xmlns:v="http://converge.i2m.dk"
          xmlns:converge="http://com.interactivemediamanagement.converge/tags">

    <ui:composition template="/WEB-INF/facelets/templates/administration.xhtml">
        <ui:define name="title">#{i18n.administrator_CalendarCategories_PAGE_TITLE}</ui:define>

        <ui:define name="body">
            <a4j:keepAlive beanName="administrator_CalendarCategories" />
            <a4j:outputPanel ajaxRendered="true">
                <v:message />
            </a4j:outputPanel>
            <h:form id="frmCalendarCategories">
                <converge:moduleHeader moduleTitle="#{i18n.administrator_CalendarCategories_CATEGORY}" />
                <div class="moduleContent">

                    <h:panelGrid columns="2" columnClasses="left, right" style="width: 100%">
                        <h:outputText value="" />
                        <a4j:commandButton id="btnNewCategory"
                                           styleClass="button mediumButton"
                                           value="#{i18n.administrator_CalendarCategories_CATEGORY_NEW}"
                                           actionListener="#{administrator_CalendarCategories.onNew}"
                                           reRender="frmEventCategoryDetails">
                            <rich:componentControl for="mpEventCategoryDetails"
                                                   operation="show"
                                                   event="oncomplete" />
                        </a4j:commandButton>
                    </h:panelGrid>



                    <rich:dataTable id="dtCalendarCategories"
                                    value="#{administrator_CalendarCategories.categories}" var="category"
                                    styleClass="table" headerClass="tableHeader"
                                    columnClasses="center columnIcon, left, left"
                                    rowClasses="odd, even">
                        <rich:column>
                            <f:facet name="header">
                                <a4j:status id="staCalendarCategories">
                                    <f:facet name="start">
                                        <h:graphicImage value="#{i18n.resource_ICON_AJAX_LOADING}" />
                                    </f:facet>
                                    <f:facet name="stop">
                                        <h:graphicImage value="#{i18n.resource_ICON_EMPTY}" width="16" height="16" />
                                    </f:facet>
                                </a4j:status>
                            </f:facet>
                            <a4j:commandLink reRender="frmEventCategoryDetails">
                                <f:setPropertyActionListener value="#{category}"
                                                             target="#{administrator_CalendarCategories.selectedCategory}" />
                                <rich:componentControl for="mpEventCategoryDetails"
                                                       operation="show"
                                                       event="oncomplete" />
                                <h:graphicImage alt="#{i18n.administrator_CalendarCategories_CATEGORY}"
                                                title="#{i18n.administrator_CalendarCategories_CATEGORY}"
                                                value="#{i18n.resource_ICON_EVENT_CATEGORY}" />
                            </a4j:commandLink>
                        </rich:column>
                        <rich:column sortBy="#{category.name}" sortOrder="ASCENDING">
                            <f:facet name="header">
                                <h:outputText value="#{i18n.administrator_CalendarCategories_CATEGORY}" />
                            </f:facet>
                            <a4j:commandLink reRender="frmEventCategoryDetails">
                                <f:setPropertyActionListener value="#{category}"
                                                             target="#{administrator_CalendarCategories.selectedCategory}" />
                                <rich:componentControl for="mpEventCategoryDetails"
                                                       operation="show"
                                                       event="oncomplete" />
                                <h:outputText value="#{category.name}" />
                            </a4j:commandLink>
                        </rich:column>
                        <rich:column sortBy="#{category.description}">
                            <f:facet name="header">
                                <h:outputText value="#{i18n.administrator_CalendarCategories_CATEGORY_DESCRIPTION}" />
                            </f:facet>
                            <h:outputText value="#{category.description}" />
                        </rich:column>
                    </rich:dataTable>
                </div>
            </h:form>

            <h:form id="frmEventCategoryDetails">
                <rich:modalPanel id="mpEventCategoryDetails" autosized="true" domElementAttachment="parent">
                    <f:facet name="header">
                        <h:panelGroup>
                            <h:outputText value="#{i18n.administrator_CalendarCategories_CATEGORY}"></h:outputText>
                        </h:panelGroup>
                    </f:facet>
                    <f:facet name="controls">
                        <h:panelGroup>
                            <h:graphicImage id="imgCloseEventCategoryDetails"
                                            value="#{i18n.resource_ICON_DIALOGUE_CLOSE}"
                                            style="link" />
                            <rich:componentControl for="mpEventCategoryDetails"
                                                   attachTo="imgCloseEventCategoryDetails"
                                                   operation="hide"
                                                   event="onclick"/>
                        </h:panelGroup>
                    </f:facet>

                    <h:panelGrid style="width: 480px;">

                        <rich:tabPanel id="tpEventCategoryDetails"
                                       switchType="client"
                                       activeTabClass="tabActive"
                                       inactiveTabClass="tabInactive">

                            <rich:tab label="#{i18n.administrator_CalendarCategories_CATEGORY}">
                                <h:panelGrid columnClasses="tabSheet" style="padding: 10px; width: 100%">
                                    <h:outputText value="#{i18n.administrator_CalendarCategories_CATEGORY_NAME}" />
                                    <h:inputText value="#{administrator_CalendarCategories.selectedCategory.name}" required="true" requiredMessage="#{i18n.administrator_CalendarCategories_CATEGORY_NAME_REQUIRED}" styleClass="text" />

                                    <h:outputText value="#{i18n.administrator_CalendarCategories_CATEGORY_DESCRIPTION}" />
                                    <h:inputTextarea value="#{administrator_CalendarCategories.selectedCategory.description}" styleClass="text mediumTextArea"/>
                                </h:panelGrid>
                            </rich:tab>
                        </rich:tabPanel>

                        <h:panelGroup styleClass="dialogueButtons">
                            <a4j:commandLink id="lnkSaveEventCategoryDetails"
                                             styleClass="dialogButton"
                                             value="#{i18n.Generic_SAVE}"
                                             actionListener="#{administrator_CalendarCategories.onSave}"
                                             reRender="frmCalendarCategories"
                                             oncomplete="if (#{converge:isAllValid()}) { Richfaces.hideModalPanel('mpEventCategoryDetails'); return false;}" />

                            <a4j:commandLink id="lnkApplyEventCategoryDetails"
                                             styleClass="dialogButton"
                                             value="#{i18n.Generic_APPLY}"
                                             reRender="frmCalendarCategories"
                                             actionListener="#{administrator_CalendarCategories.onSave}" />

                            <a4j:commandLink id="lnkDeleteEventCategoryDetails"
                                             rendered="#{administrator_CalendarCategories.editMode}"
                                             onclick="if (confirm('#{i18n.administrator_CalendarCategories_CATEGORY_PROMPT_DELETE}') != true){ return false; };"
                                             actionListener="#{administrator_CalendarCategories.onDelete}"
                                             styleClass="dialogButton"
                                             value="#{i18n.Generic_DELETE}"
                                             reRender="frmCalendarCategories">
                                <rich:componentControl for="mpEventCategoryDetails"
                                                       operation="hide"
                                                       event="oncomplete" />
                            </a4j:commandLink>

                            <h:commandLink id="lnkCancelEventCategoryDetails"
                                           styleClass="dialogButton"
                                           value="#{i18n.Generic_CANCEL}"
                                           onclick="#{rich:component('mpEventCategoryDetails')}.hide(); return false;">
                            </h:commandLink>
                        </h:panelGroup>

                    </h:panelGrid>

                </rich:modalPanel>
            </h:form>

        </ui:define>
    </ui:composition>
</jsp:root>